name: ${name}
description: ${description}
version: ${version}
author: ${author}
website: ${url}
main: org.geysermc.floodgate.SpigotPlugin
api-version: 1.13
folia-supported: true
softdepend:
  - DreamEngine
commands:
  neteasebind:
    description: 梦想之城账号互通命令
    aliases:
      - nbind
